# Stage 1: auth
FROM node:22.20-alpine3.21 AS auth-builder
WORKDIR /auth
COPY packages/auth/package.json ./
RUN npm install
COPY packages/auth ./
RUN npm run build

# Stage 2: Production
FROM node:22.20-alpine3.21 AS production
WORKDIR /app
COPY --from=auth-builder /auth /app
COPY --from=auth-builder /auth/dist /app/dist
EXPOSE 3004
CMD ["node", "dist/main.js"]