# Stage 1: widget
FROM node:22.20-alpine3.21 AS widget-builder
WORKDIR /app/widget-auth
COPY packages/widget-auth/package.json ./
RUN npm install
COPY packages/widget-auth ./
RUN sed -i "s|distDir: '../backend/views/widget'|distDir: './out'|g" next.config.ts
RUN npm run build

# # Stage 2: mini widget
# FROM node:22.20-alpine3.21 AS mini-widget-builder
# WORKDIR /miniWidget
# COPY packages/miniWidget/package.json ./
# RUN npm install
# COPY packages/miniWidget ./
# RUN npm run build:umd

# Stage 4: backend
FROM node:22-bookworm-slim AS backend-builder
WORKDIR /backend

RUN apt-get update -y && apt-get install -y \
  python3 \
  make \
  g++ \
  && rm -rf /var/lib/apt/lists/*

COPY packages/backend/package.json ./
RUN npm install
COPY packages/backend ./
RUN npx prisma generate
RUN npm run build

# Stage 5: Production
FROM node:22-bookworm-slim AS production
ARG AUTH_TOKEN=""
ENV AUTH_TOKEN=${AUTH_TOKEN}

WORKDIR /app

RUN apt-get update -y && apt-get install -y \
  python3 \
  make \
  g++ \
  && rm -rf /var/lib/apt/lists/*

COPY --from=backend-builder /backend/package*.json ./
COPY --from=backend-builder /backend/dist ./dist
COPY --from=backend-builder /backend/i18n ./dist/i18n
COPY --from=backend-builder /backend/node_modules ./node_modules
COPY --from=backend-builder /backend/prisma ./prisma
COPY --from=backend-builder /backend/public ./public
COPY --from=backend-builder /backend/views ./views
COPY --from=widget-builder /app/widget-auth/out ./views/widget
RUN npm rebuild bcrypt --build-from-source
# COPY --from=mini-widget-builder /backend/auth/ /app/auth/
EXPOSE 3005
CMD ["node", "dist/main.js"]
