export const LOG_EVENTS = {
  AUTH: {
    LOGIN_ATTEMPT: 'LOGIN_ATTEMPT',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT: 'LOGOUT',
    TOKEN_ISSUED: 'TOKEN_ISSUED',
    TOKEN_REVOKED: 'TOKEN_REVOKED',
    SESSION_CREATED: 'SESSION_CREATED',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    MFA_REQUESTED: 'MFA_REQUESTED',
    MFA_COMPLETED: 'MFA_COMPLETED',
  },

  SECURITY: {
    PASSWORD_CHANGED: 'PASSWORD_CHANGED',
    PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
    SUSPICIOUS_LOGIN: 'SUSPICIOUS_LOGIN',
    IP_BLOCKED: 'IP_BLOCKED',
    ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  },

  PROFILE: {
    PROFILE_UPDATED: 'PROFILE_UPDATED',
    EMAIL_CHANGED: 'EMAIL_CHANGED',
    PHONE_CHANGED: 'PHONE_CHANGED',
    MFA_ENABLED: 'MFA_ENABLED',
    MFA_DISABLED: 'MFA_DISABLED',
  },

  CLIENT: {
    CLIENT_REGISTERED: 'CLIENT_REGISTERED',
    CLIENT_UPDATED: 'CLIENT_UPDATED',
    CLIENT_REMOVED: 'CLIENT_REMOVED',
    SCOPE_GRANTED: 'SCOPE_GRANTED',
    SCOPE_REVOKED: 'SCOPE_REVOKED',
  },

  INTEGRATION: {
    PROVIDER_ADDED: 'PROVIDER_ADDED',
    PROVIDER_REMOVED: 'PROVIDER_REMOVED',
    EXTERNAL_LOGIN: 'EXTERNAL_LOGIN',
    ACCOUNT_LINKED: 'ACCOUNT_LINKED',
    ACCOUNT_UNLINKED: 'ACCOUNT_UNLINKED',
  },
};
